### PR TITLE
Remove deprecated

### PR DESCRIPTION
**Pull request by campbeb**

### CODE REVIEW

**Comment by campbeb** [comment]
Sorry, didn't meant to push to your branch.

**Comment by kinverarity1** [comment]
No problem :-)

FYI, if you're interested in submitting a PR at some point for this project, I should let you know that I lost the private key with which the APKs for this package were signed with. As a consequence I can no longer update the app's current page on Google Play.

The only way to release an update would be to change the package name from `com.kinverarity.offlinebookshelfbrowser` to something new (which I'm happy to do).

**Comment by campbeb** [comment]
I was just hacking on it for myself as I wasn't sure how much interest there still was in developing it since it seemed a little dormant, aside from your conversion to gradle.
I can certainly submit some pull requests if you think people are still using the app.

**Comment by kinverarity1** [comment]
I had a few changes of phone and computer and it took quite some time to get it building successfully again. Only to then find I had lost the APK key!

Certainly if you have any PRs I will change the package name and distribute them to the Play Store. Thanks for the interest!

**Pull request closed without merging**
